# Generated by Django 3.2.8 on 2021-10-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(default='desk', upload_to='images/', verbose_name='Изображение_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение_2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение_3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение_4'),
        ),
    ]
